### ISSUE TITLE
Multiple bam support...

### ISSUE THREAD

**Issue by travc** [papaemmelab/split_bed_by_index#2]
This is a big ask, but even if you don't end up doing it, I'd appreciate hearing your thoughts on how it might be done...

For multiple sample joint calling, it would be awesome to be able to run this tool on multiple bam files and chunk based on the estimate total number of reads in all of them.

**Comment by mflevine** [comment]
Hi, you can take a look at https://github.com/brentp/goleft/tree/master/indexsplit#indexsplit which is what inspired this tool. This tool splits into an N number of splits across a cohort instead of N number of reads. Does this suit your use case?

**Comment by travc** [comment]
Looks like it might be what I need.  Thanks

Actually, is there a functional difference between `goleft indexsplit` running on a single bam and `split_bed_by_index`?

**Comment by mflevine** [comment]
The difference is that `goleft indexsplit` splits into a set number of chunks while `split_bed_by_index` will split into a variable amount of chunks depending on the size of the bam. We use this with variant calling to try to keep the processing of each chunk under a maximum runtime.

**Comment by travc** [comment]
Same usecase here, but with multiple samples.
If I get the time and energy to modify it, seems like `indexsplit` could be made to split based on a maximum data size instead of number of chunks.  Would probably be simpler even.

If it was written in python, C, or C++, I'd probably do that right now, but I don't feel like figuring out the compiler install and syntax peculiarities of yet another language at the moment (especially one with automagic remote imports).

Anyways, thanks for pointing out the tool and the clarification.
